// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhxkfyqxhqxfsjkobcdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoeGtmeXF4aHF4ZnNqa29iY2RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTk4NTksImV4cCI6MjA2NjI3NTg1OX0.Hec39Gi-G5fPXpBJIgVIl25V0CPsztLy1nVj3XNK5oI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);